feat:add kitex template
cloudwego/kitex-examples pull request #88
Opened 2023-12-13 12:19 UTC by ViolaPioggia

#### What type of PR is this?
feat
#### Check the PR title.
feat:add kitex template
#### (Optional) Translate the PR title into Chinese.
增加 template 模版的示例

2023-12-14 07:21 UTC, felix021 commented on kitex/template/go.mod
> +replace github.com/apache/thrift => github.com/apache/thrift v0.13.0
no dependency?

2023-12-14 07:21 UTC, felix021 commented on kitex/template/readme_zn.md
> +sh 构建.sh
file names shouldn't be translated.

2023-12-14 07:21 UTC, felix021 commented on kitex/template/script/bootstrap.sh
> +exec "$CURDIR/bin/"
doesn't seem capable of executing the binary.

2023-12-14 07:21 UTC, felix021 commented on kitex/template/template/bootstrap_sh_tpl.yaml
> +  exec "$CURDIR/bin/{{.RealServiceName}}"
So where is the RealServiceName assigned?

2023-12-14 07:21 UTC, felix021 commented on kitex/template/template/bootstrap_sh_tpl.yaml
> +  exec "$CURDIR/bin/{{.RealServiceName}}"
Try to make it simpler to avoid confusion

2023-12-14 07:21 UTC, felix021 commented on kitex/template/conf/dev/conf.yaml
> +  service: ""
service name is also missing

2023-12-17 09:59 UTC, AsterDY commented on kitex/template/.gitignore
目录结构把template放到生成的demo里面有点奇怪，能不能把生成代码再包一层文件夹和template并列

2023-12-17 09:59 UTC, AsterDY commented on README_CN.md
> +- [template](kitex/template) 使用 kitex 自定义模版生成服务端代码的示例
然后kitex/template再加一个reame或者script说明一下怎么使用这个tmpl生成吧

2023-12-17 10:27 UTC, ViolaPioggia commented on README_CN.md
> +- [template](kitex/template) 使用 kitex 自定义模版生成服务端代码的示例
template 目录下有 makefile 文件

2023-12-17 10:28 UTC, ViolaPioggia commented on kitex/template/.gitignore
hertz-example 里就是这样安排的，是根据 template 模版直接生成的代码

2023-12-17 10:39 UTC, li-jin-gou requested changes
CI 没过

2023-12-17 12:07 UTC, li-jin-gou approved these changes

2023-12-17 12:07 UTC, merged