feat: add README_ZN
cloudwego/kitex-examples pull request #92
Opened 2024-01-02 14:58 UTC by ViolaPioggia

#### What type of PR is this?
feat
#### Check the PR title.
feat: add README_ZN

2024-01-03 08:19 UTC, HeyJavaBean submitted a review, later dismissed

2024-01-06 03:24 UTC, AsterDY submitted a review, later dismissed

2024-01-06 09:58 UTC, cqqqq777 requested changes

2024-01-06 09:58 UTC, cqqqq777 commented on bizdemo/easy_note/README.md
> +English | [中文](./README_CN)
这里中文的链接有问题，少了个 .md

2024-01-06 09:58 UTC, cqqqq777 commented on klog/README.md
>  You can learn about how to use Kitex klog
加个换行好一点

2024-01-06 09:58 UTC, cqqqq777 commented on klog/README_CN.md
> +您可以了解如何使用 Kitex klog
同英文

2024-01-06 09:58 UTC, cqqqq777 commented on opentelemetry/README_CN.md
> +### 通过 Context 记录日志
通过 Context 记录日志 -> 日志与 Context 关联 感觉好一点

2024-01-06 09:58 UTC, cqqqq777 commented on opentelemetry/README_CN.md
> +### 查看跟踪
跟踪 -> 链路 感觉好一点

2024-01-06 09:58 UTC, cqqqq777 commented on opentelemetry/README_CN.md
> +## 追踪相关日志
同上

2024-01-06 09:58 UTC, cqqqq777 commented on prometheus/README_CN.md
> +3. Prometheus 和 Grafana
加一个运行

2024-01-06 09:58 UTC, cqqqq777 commented on proxyless/README_CN.md
> +kubectl 标签命名空间无代理 istio-injection-
kubectl label namespace proxyless istio-injection-

2024-01-06 09:58 UTC, cqqqq777 commented on proxyless/README_CN.md
> +kubectl get 命名空间 -L istio-injection
kubectl get namespace -L istio-injection

2024-01-06 09:58 UTC, cqqqq777 commented on proxyless/README_CN.md
> +# 将来可能会将脚本替换为使用k8s客户端的代码来控制整个部署。
k8s 跟中文之间需要空格

2024-01-06 09:58 UTC, cqqqq777 commented on proxyless/README_CN.md
> +* 使用 kubectl 日志检查 kitex-client 的日志
kubectl 日志 -> kubectl logs

2024-01-06 09:58 UTC, cqqqq777 commented on tracer/README_CN.md
> +2. 运行jaeger all-in-one
中英文之间需要空格

2024-01-06 09:58 UTC, cqqqq777 commented on tracer/README_CN.md
> +打开另一个终端并运行 `sh client/opentracing/run.sh`
这个文档的换行有点问题，英文文档也是，可以修改一下

2024-01-06 13:08 UTC, AsterDY approved these changes

2024-01-06 13:19 UTC, AsterDY approved these changes

2024-01-06 13:20 UTC, merged